services:
  website:
    build: .
    ports:
      - "0.0.0.0:5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - db
    networks:
      - public
      - internal
    volumes:
      - ./templates:/app/templates

  db:
    image: mariadb:10.8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: notes_db
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - internal

networks:
  public:
  internal:

volumes:
  mariadb_data:
